<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:include filename="$(find food_serving_robot)/urdf/left_arm.trans"/>

  <xacro:macro name="cylinder_inertial" params="radius length mass *origin">
    <inertial>
      <mass value="${mass}" />
      <xacro:insert_block name="origin" />
      <inertia ixx="${0.0833333 * mass * (3 * radius * radius + length * length)}" ixy="0.0" ixz="0.0"
        iyy="${0.0833333 * mass * (3 * radius * radius + length * length)}" iyz="0.0"
        izz="${0.5 * mass * radius * radius}" />
    </inertial>
  </xacro:macro>

    <xacro:property name="l_base_mass" value="4.0" /> 
    <xacro:property name="shoulder_mass" value="7.778" />
    <xacro:property name="upper_arm_mass" value="12.93" />
    <xacro:property name="forearm_mass" value="3.87" />
    <xacro:property name="wrist_1_mass" value="1.96" />
    <xacro:property name="wrist_2_mass" value="1.96" />
    <xacro:property name="wrist_3_mass" value="0.202" />
    <xacro:property name="shoulder_cog" value="0.00008 0.00244 -0.037" />
    <xacro:property name="upper_arm_cog" value="0.00001 0.15061 0.38757" />
    <xacro:property name="forearm_cog" value="-0.00012 0.06112 0.1984" />
    <xacro:property name="wrist_1_cog" value="-0.00021 -0.00112 0.02269" />
    <xacro:property name="wrist_2_cog" value="-0.00021 0.00112 0.002269" />
    <xacro:property name="wrist_3_cog" value="0 -0.001156 -0.00149" />
    <xacro:property name="d1" value="0.1273" />
    <xacro:property name="a2" value="-0.612" />
    <xacro:property name="a3" value="-0.5723" />
    <xacro:property name="d4" value="0.163941" />
    <xacro:property name="d5" value="0.1157" />
    <xacro:property name="d6" value="0.0922" />
    <xacro:property name="shoulder_offset" value="0.220941" /> 
    <xacro:property name="elbow_offset" value="-0.1719" />
    <xacro:property name="upper_arm_inertia_offset" value="0.045" /> 
    <xacro:property name="shoulder_height" value="${d1}" />
    <xacro:property name="upper_arm_length" value="${-a2}" />
    <xacro:property name="forearm_length" value="${-a3}" />
    <xacro:property name="wrist_1_length" value="${d4 - elbow_offset - shoulder_offset}" />
    <xacro:property name="wrist_2_length" value="${d5}" />
    <xacro:property name="wrist_3_length" value="${d6}" />

    <link name="l_shoulder_hinge" >
      <visual>
        <geometry>
          <mesh filename="package://food_serving_robot/meshes/ur10/visual/base.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://food_serving_robot/meshes/ur10/collision/base.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.038" mass="${l_base_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="l_shoulder_pan_joint" type="revolute">
      <parent link="l_shoulder_hinge" />
      <child link = "l_shoulder_link" />
      <origin xyz="0.0 0.0 ${shoulder_height}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 0 1" />
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="330.0" velocity="2.16"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="l_shoulder_link">
      <visual>
        <geometry>
          <mesh filename="package://food_serving_robot/meshes/ur10/visual/shoulder.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://food_serving_robot/meshes/ur10/collision/shoulder.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.178" mass="${shoulder_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="l_shoulder_lift_joint" type="revolute">
      <parent link="l_shoulder_link" />
      <child link = "l_upper_arm_link" />
      <origin xyz="0.0 ${shoulder_offset} 0.0" rpy="0.0 ${pi / 2.0} 0.0" />
      <axis xyz="0 1 0" />
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="330.0" velocity="2.16"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="l_upper_arm_link">
      <visual>
        <geometry>
          <mesh filename="package://food_serving_robot/meshes/ur10/visual/upperarm.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://food_serving_robot/meshes/ur10/collision/upperarm.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="${-a2}" mass="${upper_arm_mass}">
        <origin xyz="0.0 ${-upper_arm_inertia_offset} ${-a2/2.0}" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="l_elbow_joint" type="revolute">
      <parent link="l_upper_arm_link" />
      <child link = "l_forearm_link" />
      <origin xyz="0.0 ${elbow_offset} ${upper_arm_length}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 1 0" />
        <limit lower="${-pi}" upper="${pi}" effort="150.0" velocity="3.15"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="l_forearm_link">
      <visual>
         <geometry>
          <mesh filename="package://food_serving_robot/meshes/ur10/visual/forearm.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://food_serving_robot/meshes/ur10/collision/forearm.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="${-a3}" mass="${forearm_mass}">
        <origin xyz="0.0 0.0 ${-a3/2.0}" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="l_wrist_1_joint" type="revolute">
      <parent link="l_forearm_link" />
      <child link = "l_wrist_1_link" />
      <origin xyz="0.0 0.0 ${forearm_length}" rpy="0.0 ${pi / 2.0} 0.0" />
      <axis xyz="0 1 0" />
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="l_wrist_1_link">
      <visual>
        <geometry>
          <mesh filename="package://food_serving_robot/meshes/ur10/visual/wrist1.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://food_serving_robot/meshes/ur10/collision/wrist1.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.12" mass="${wrist_1_mass}">
        <origin xyz="0.0 ${wrist_1_length} 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="l_wrist_2_joint" type="revolute">
      <parent link="l_wrist_1_link" />
      <child link = "l_wrist_2_link" />
      <origin xyz="0.0 ${wrist_1_length} 0.0" rpy="0.0 0.0 0.0" />
      <axis xyz="0 0 1" />
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="l_wrist_2_link">
      <visual>
        <geometry>
          <mesh filename="package://food_serving_robot/meshes/ur10/visual/wrist2.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://food_serving_robot/meshes/ur10/collision/wrist2.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.12" mass="${wrist_2_mass}">
        <origin xyz="0.0 0.0 ${wrist_2_length}" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="l_wrist_3_joint" type="revolute">
      <parent link="l_wrist_2_link" />
      <child link = "l_wrist_3_link" />
      <origin xyz="0.0 0.0 ${wrist_2_length}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 1 0" />
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="l_wrist_3_link">
      <visual>
        <geometry>
          <mesh filename="package://food_serving_robot/meshes/ur10/visual/wrist3.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://food_serving_robot/meshes/ur10/collision/wrist3.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.045" length="0.0305" mass="${wrist_3_mass}">
        <origin xyz="0.0 ${wrist_3_length - 0.0305/2} 0.0" rpy="${pi/2} 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="l_gripper_base_joint" type="fixed">
      <origin xyz="0 ${wrist_3_length} 0" rpy="${pi/-2.0} 0 0"/>
      <parent link="l_wrist_3_link"/>
      <child link="l_gripper_link"/>
    </joint>

    <link
    name="l_gripper_link">
    <inertial>
      <origin
        xyz="3.2532E-08 -0.0066779 0.028667"
        rpy="0 0 0" />
      <mass
        value="0.077569" />
      <inertia
        ixx="3.46E-05"
        ixy="8.6277E-10"
        ixz="3.1185E-11"
        iyy="3.355E-05"
        iyz="-1.8724E-06"
        izz="2.4211E-05" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://food_serving_robot/meshes/gripper_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79216 0.81961 0.93333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://food_serving_robot/meshes/gripper_link.STL" />
      </geometry>
    </collision>
  </link>
  <link
    name="l_finger_link">
    <inertial>
      <origin
        xyz="-0.0065946 0.048233 -0.015"
        rpy="0 0 0" />
      <mass
        value="0.023068" />
      <inertia
        ixx="1.9174E-05"
        ixy="4.9044E-06"
        ixz="1.9121E-22"
        iyy="2.1843E-06"
        iyz="-3.4773E-22"
        izz="2.054E-05" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://food_serving_robot/meshes/finger_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.50196 0.50196 0.50196 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://food_serving_robot/meshes/finger_link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="l_finger_joint"
    type="revolute">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent
      link="l_gripper_link" />
    <child
      link="l_finger_link" />
    <axis
      xyz="1 0 0" />
    <limit
      lower="-1"
      upper="1"
      effort="50"
      velocity="0" />
  </joint>

    <gazebo reference="l_shoulder_link">
      <selfCollide>true</selfCollide>
    </gazebo>
    <gazebo reference="l_upper_arm_link">
      <selfCollide>true</selfCollide>
    </gazebo>
    <gazebo reference="l_forearm_link">
      <selfCollide>true</selfCollide>
    </gazebo>
    <gazebo reference="l_wrist_1_link">
      <selfCollide>true</selfCollide>
    </gazebo>
    <gazebo reference="l_wrist_3_link">
      <selfCollide>true</selfCollide>
    </gazebo>
    <gazebo reference="l_wrist_2_link">
      <selfCollide>true</selfCollide>
    </gazebo>
    <gazebo reference="l_ee_link">
      <selfCollide>true</selfCollide>
    </gazebo>
</robot>
